name: Deploy Flask App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Install Flask and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flask 
      - name: Install Flask Session
      run: |
        python -m pip install --upgrade flask_session

      - name: Build the Flask app
        run: |
          python app.py build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path/to/your/flask/app/static
